### ISSUE TITLE
[Feature Request] Hide interfaces

### ISSUE THREAD

**Issue by Fade78** [marcinjahn/gnome-quicksettings-audio-devices-renamer-extension#3]
Hello,
Thanks for this helpful extension. I have a lot of interfaces (mainly because I have audio interfaces, because I make music on my computer). In the linux desktop I only use two of them. It would be great if, in addition to renaming interfaces, your extension allowed to select which one to actually display so the choice is easy and quick.

**Comment by Fade78** [comment]
Never mind, found your other extension :-)
https://github.com/marcinjahn/gnome-quicksettings-audio-devices-hider-extension

**Comment by marcinjahn** [comment]
Glad I could help 😄
