### ISSUE TITLE
Gnome 46

### ISSUE THREAD

**Issue by mtompkins** [marcinjahn/gnome-quicksettings-audio-devices-renamer-extension#4]
Would love to see this updated for Gnome 46

**Comment by marcinjahn** [comment]
Hi @mtompkins, my answer would be the same as in https://github.com/marcinjahn/gnome-quicksettings-audio-devices-hider-extension/issues/11#issuecomment-2023148728.

I'd love to update it, but I don't have time to test it at the moment.

**Comment by marcinjahn** [comment]
Updated, the new version is already available on https://extensions.gnome.org/extension/6000/quick-settings-audio-devices-renamer/.
