### ISSUE TITLE
Not applying to panels on non-primary monitors

### ISSUE THREAD

**Issue by howels** [marcinjahn/gnome-quicksettings-audio-devices-renamer-extension#6]
Extension is great, but only works for the audio devices shown in the quick settings on my primary monitor. Other monitors quick settings still show the original names.

**Comment by marcinjahn** [comment]
And I guess you’re seeing panels on other monitors thanks to some other extension, right?

**Comment by howels** [comment]
> And I guess you’re seeing panels on other monitors thanks to some other extension, right?

I checked "Display panels on all monitors" in Dash to Panel.

**Comment by marcinjahn** [comment]
Right. There are lots of extensions out there, each one introducing its own quirks. I’m not planning to introduce compatibility with other extensions, since it’d become really hard to maintain, especially when I don’t even use these other extensions.  Sorry, won’t do I’m afraid.

**Comment by howels** [comment]
> > Will report this in Dash to Panel if it's not due to your plugin.
> 
> I don’t think they’ll be able to/want to help either, because it’s not really something they can do. the issue is that the desktop renders the panel twice, while my extension only replaces the sound entries in one native panel.

Seems to affect a few plugins, now I look I see that the additional dash-to-panel panels are running a bare-bones set of components and other plugins don't apply there either.
